[
  {
    adult: false,
    backdrop_path: "/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg",
    belongs_to_collection: null,
    budget: 18000000,
    genres: [
      { id: 27, name: "Horror" },
      { id: 9648, name: "Mystery" },
      { id: 53, name: "Thriller" },
    ],
    homepage: "https://www.thepopes-exorcist.movie",
    id: 758323,
    imdb_id: "tt13375076",
    original_language: "en",
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    popularity: 4935.809,
    poster_path: "/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
    production_companies: [
      {
        id: 3287,
        logo_path: "/bz6GbCQQXGNE56LTW9dwgksW0Iw.png",
        name: "Screen Gems",
        origin_country: "US",
      },
      {
        id: 84792,
        logo_path: "/7Rfr3Zu6QnHpXW2VdSEzUminAQd.png",
        name: "2.0 Entertainment",
        origin_country: "US",
      },
      { id: 177894, logo_path: null, name: "Jesus & Mary", origin_country: "" },
      {
        id: 177895,
        logo_path: null,
        name: "Worldwide Katz",
        origin_country: "",
      },
      {
        id: 177896,
        logo_path: null,
        name: "Loyola Productions",
        origin_country: "",
      },
      { id: 194987, logo_path: null, name: "FFILME.RO", origin_country: "" },
    ],
    production_countries: [
      { iso_3166_1: "ES", name: "Spain" },
      { iso_3166_1: "GB", name: "United Kingdom" },
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2023-04-05",
    revenue: 61675816,
    runtime: 103,
    spoken_languages: [
      { english_name: "German", iso_639_1: "de", name: "Deutsch" },
      { english_name: "Spanish", iso_639_1: "es", name: "Español" },
      { english_name: "English", iso_639_1: "en", name: "English" },
      { english_name: "Italian", iso_639_1: "it", name: "Italiano" },
      { english_name: "Latin", iso_639_1: "la", name: "Latin" },
    ],
    status: "Released",
    tagline:
      "Inspired by the actual files of Father Gabriele Amorth, Chief Exorcist of the Vatican.",
    title: "The Pope's Exorcist",
    video: false,
    vote_average: 7.447,
    vote_count: 470,
  },
  {
    adult: false,
    backdrop_path: "/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
    belongs_to_collection: null,
    budget: 0,
    genres: [{ id: 28, name: "Action" }],
    homepage: "",
    id: 1048300,
    imdb_id: "tt14012572",
    original_language: "en",
    original_title: "Adrenaline",
    overview:
      "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
    popularity: 820.208,
    poster_path: "/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
    production_companies: [],
    production_countries: [],
    release_date: "2022-12-15",
    revenue: 0,
    runtime: 75,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "",
    title: "Adrenaline",
    video: false,
    vote_average: 5.871,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
    belongs_to_collection: null,
    budget: 0,
    genres: [{ id: 28, name: "Action" }],
    homepage: "",
    id: 1048300,
    imdb_id: "tt14012572",
    original_language: "en",
    original_title: "Adrenaline",
    overview:
      "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
    popularity: 820.208,
    poster_path: "/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
    production_companies: [],
    production_countries: [],
    release_date: "2022-12-15",
    revenue: 0,
    runtime: 75,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "",
    title: "Adrenaline",
    video: false,
    vote_average: 5.871,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
    belongs_to_collection: null,
    budget: 0,
    genres: [{ id: 28, name: "Action" }],
    homepage: "",
    id: 1048300,
    imdb_id: "tt14012572",
    original_language: "en",
    original_title: "Adrenaline",
    overview:
      "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
    popularity: 820.208,
    poster_path: "/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
    production_companies: [],
    production_countries: [],
    release_date: "2022-12-15",
    revenue: 0,
    runtime: 75,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "",
    title: "Adrenaline",
    video: false,
    vote_average: 5.871,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
    belongs_to_collection: null,
    budget: 0,
    genres: [{ id: 28, name: "Action" }],
    homepage: "",
    id: 1048300,
    imdb_id: "tt14012572",
    original_language: "en",
    original_title: "Adrenaline",
    overview:
      "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
    popularity: 820.208,
    poster_path: "/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
    production_companies: [],
    production_countries: [],
    release_date: "2022-12-15",
    revenue: 0,
    runtime: 75,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "",
    title: "Adrenaline",
    video: false,
    vote_average: 5.871,
    vote_count: 35,
  },
];
